package com.android.billingclient.api;
final class zzcj {
    static final com.android.billingclient.api.BillingResult zzA;
    static final com.android.billingclient.api.BillingResult zzB;
    static final com.android.billingclient.api.BillingResult zzC;
    static final com.android.billingclient.api.BillingResult zzD;
    static final com.android.billingclient.api.BillingResult zzE;
    static final com.android.billingclient.api.BillingResult zzF;
    public static final synthetic int zzG;
    static final com.android.billingclient.api.BillingResult zza;
    static final com.android.billingclient.api.BillingResult zzb;
    static final com.android.billingclient.api.BillingResult zzc;
    static final com.android.billingclient.api.BillingResult zzd;
    static final com.android.billingclient.api.BillingResult zze;
    static final com.android.billingclient.api.BillingResult zzf;
    static final com.android.billingclient.api.BillingResult zzg;
    static final com.android.billingclient.api.BillingResult zzh;
    static final com.android.billingclient.api.BillingResult zzi;
    static final com.android.billingclient.api.BillingResult zzj;
    static final com.android.billingclient.api.BillingResult zzk;
    static final com.android.billingclient.api.BillingResult zzl;
    static final com.android.billingclient.api.BillingResult zzm;
    static final com.android.billingclient.api.BillingResult zzn;
    static final com.android.billingclient.api.BillingResult zzo;
    static final com.android.billingclient.api.BillingResult zzp;
    static final com.android.billingclient.api.BillingResult zzq;
    static final com.android.billingclient.api.BillingResult zzr;
    static final com.android.billingclient.api.BillingResult zzs;
    static final com.android.billingclient.api.BillingResult zzt;
    static final com.android.billingclient.api.BillingResult zzu;
    static final com.android.billingclient.api.BillingResult zzv;
    static final com.android.billingclient.api.BillingResult zzw;
    static final com.android.billingclient.api.BillingResult zzx;
    static final com.android.billingclient.api.BillingResult zzy;
    static final com.android.billingclient.api.BillingResult zzz;

    static zzcj()
    {
        com.android.billingclient.api.BillingResult$Builder v0_0 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_0.setResponseCode(3);
        v0_0.setDebugMessage("Google Play In-app Billing API version is less than 3");
        v0_0.build();
        com.android.billingclient.api.BillingResult$Builder v0_60 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_60.setResponseCode(3);
        v0_60.setDebugMessage("Google Play In-app Billing API version is less than 9");
        com.android.billingclient.api.zzcj.zza = v0_60.build();
        com.android.billingclient.api.zzcj.zzb = v1.a.d(3, "Billing service unavailable on device.");
        com.android.billingclient.api.zzcj.zzc = v1.a.d(2, "Billing service unavailable on device.");
        com.android.billingclient.api.zzcj.zzd = v1.a.d(5, "Client is already in the process of connecting to billing service.");
        com.android.billingclient.api.BillingResult$Builder v0_45 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_45.setResponseCode(5);
        v0_45.setDebugMessage("The list of SKUs can\'t be empty.");
        v0_45.build();
        com.android.billingclient.api.BillingResult$Builder v0_46 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_46.setResponseCode(5);
        v0_46.setDebugMessage("SKU type can\'t be empty.");
        v0_46.build();
        com.android.billingclient.api.BillingResult$Builder v0_47 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_47.setResponseCode(5);
        v0_47.setDebugMessage("Product type can\'t be empty.");
        com.android.billingclient.api.zzcj.zze = v0_47.build();
        com.android.billingclient.api.zzcj.zzf = v1.a.d(-2, "Client does not support extra params.");
        com.android.billingclient.api.zzcj.zzg = v1.a.d(5, "Invalid purchase token.");
        com.android.billingclient.api.zzcj.zzh = v1.a.d(6, "An internal error occurred.");
        com.android.billingclient.api.BillingResult$Builder v0_55 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_55.setResponseCode(5);
        v0_55.setDebugMessage("SKU can\'t be null.");
        v0_55.build();
        com.android.billingclient.api.BillingResult$Builder v0_56 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_56.setResponseCode(0);
        com.android.billingclient.api.zzcj.zzi = v0_56.build();
        com.android.billingclient.api.zzcj.zzj = v1.a.d(-1, "Service connection is disconnected.");
        com.android.billingclient.api.zzcj.zzk = v1.a.d(2, "Timeout communicating with service.");
        com.android.billingclient.api.zzcj.zzl = v1.a.d(-2, "Client does not support subscriptions.");
        com.android.billingclient.api.zzcj.zzm = v1.a.d(-2, "Client does not support subscriptions update.");
        com.android.billingclient.api.BillingResult$Builder v0_67 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_67.setResponseCode(-2);
        v0_67.setDebugMessage("Client does not support get purchase history.");
        v0_67.build();
        com.android.billingclient.api.BillingResult$Builder v0_68 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_68.setResponseCode(-2);
        v0_68.setDebugMessage("Client does not support price change confirmation.");
        com.android.billingclient.api.zzcj.zzn = v0_68.build();
        com.android.billingclient.api.zzcj.zzo = v1.a.d(-2, "Play Store version installed does not support cross selling products.");
        com.android.billingclient.api.zzcj.zzp = v1.a.d(-2, "Client does not support multi-item purchases.");
        com.android.billingclient.api.zzcj.zzq = v1.a.d(-2, "Client does not support offer_id_token.");
        com.android.billingclient.api.zzcj.zzr = v1.a.d(-2, "Client does not support ProductDetails.");
        com.android.billingclient.api.zzcj.zzs = v1.a.d(-2, "Client does not support in-app messages.");
        com.android.billingclient.api.BillingResult$Builder v0_12 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_12.setResponseCode(-2);
        v0_12.setDebugMessage("Client does not support user choice billing.");
        v0_12.build();
        com.android.billingclient.api.BillingResult$Builder v0_14 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_14.setResponseCode(-2);
        v0_14.setDebugMessage("Play Store version installed does not support external offer.");
        com.android.billingclient.api.zzcj.zzt = v0_14.build();
        com.android.billingclient.api.zzcj.zzu = v1.a.d(-2, "Play Store version installed does not support multi-item purchases with season pass in one cart.");
        com.android.billingclient.api.zzcj.zzv = v1.a.d(-2, "Play Store version installed does not support querying AutoPay plan purchase.");
        com.android.billingclient.api.zzcj.zzw = v1.a.d(-2, "Play Store version installed does not support including suspended subscriptions.");
        com.android.billingclient.api.zzcj.zzx = v1.a.d(5, "Unknown feature");
        com.android.billingclient.api.zzcj.zzy = v1.a.d(-2, "Play Store version installed does not support get billing config.");
        com.android.billingclient.api.zzcj.zzz = v1.a.d(-2, "Query product details with serialized docid is not supported.");
        com.android.billingclient.api.zzcj.zzA = v1.a.d(-2, "Play Store version installed does not support launching external offer flow.");
        com.android.billingclient.api.zzcj.zzB = v1.a.d(4, "Item is unavailable for purchase.");
        com.android.billingclient.api.zzcj.zzC = v1.a.d(-2, "Query product details with developer specified account is not supported.");
        com.android.billingclient.api.zzcj.zzD = v1.a.d(-2, "Play Store version installed does not support alternative billing only.");
        com.android.billingclient.api.zzcj.zzE = v1.a.d(5, "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        com.android.billingclient.api.zzcj.zzF = v1.a.d(6, "An error occurred while retrieving billing override.");
        com.android.billingclient.api.BillingResult$Builder v0_41 = com.android.billingclient.api.BillingResult.newBuilder();
        v0_41.setResponseCode(-2);
        v0_41.setDebugMessage("Play Store version installed does not support the provided billing program.");
        v0_41.build();
        return;
    }

    public static com.android.billingclient.api.BillingResult zza(int p0, String p1)
    {
        return v1.a.d(p0, p1);
    }
}
