package com.google.android.recaptcha.internal;
public final class zzba {
    public static final com.google.android.recaptcha.internal.zzba zzA;
    public static final com.google.android.recaptcha.internal.zzba zzB;
    public static final com.google.android.recaptcha.internal.zzba zzC;
    public static final com.google.android.recaptcha.internal.zzba zzD;
    public static final com.google.android.recaptcha.internal.zzba zzE;
    public static final com.google.android.recaptcha.internal.zzba zzF;
    public static final com.google.android.recaptcha.internal.zzba zzG;
    public static final com.google.android.recaptcha.internal.zzba zzH;
    public static final com.google.android.recaptcha.internal.zzba zzI;
    public static final com.google.android.recaptcha.internal.zzba zzJ;
    public static final com.google.android.recaptcha.internal.zzba zzK;
    public static final com.google.android.recaptcha.internal.zzba zzL;
    public static final com.google.android.recaptcha.internal.zzba zzM;
    public static final com.google.android.recaptcha.internal.zzba zzN;
    public static final com.google.android.recaptcha.internal.zzba zzO;
    public static final com.google.android.recaptcha.internal.zzba zzP;
    public static final com.google.android.recaptcha.internal.zzba zzQ;
    public static final com.google.android.recaptcha.internal.zzba zzR;
    public static final com.google.android.recaptcha.internal.zzba zzS;
    public static final com.google.android.recaptcha.internal.zzba zzT;
    public static final com.google.android.recaptcha.internal.zzba zzU;
    public static final com.google.android.recaptcha.internal.zzba zzV;
    public static final com.google.android.recaptcha.internal.zzba zzW;
    public static final com.google.android.recaptcha.internal.zzba zzX;
    public static final com.google.android.recaptcha.internal.zzba zzY;
    public static final com.google.android.recaptcha.internal.zzba zzZ;
    public static final com.google.android.recaptcha.internal.zzba zza;
    public static final com.google.android.recaptcha.internal.zzba zzaa;
    public static final com.google.android.recaptcha.internal.zzba zzab;
    public static final com.google.android.recaptcha.internal.zzba zzac;
    public static final com.google.android.recaptcha.internal.zzba zzad;
    public static final com.google.android.recaptcha.internal.zzba zzae;
    public static final com.google.android.recaptcha.internal.zzba zzaf;
    public static final com.google.android.recaptcha.internal.zzba zzag;
    public static final com.google.android.recaptcha.internal.zzba zzah;
    public static final com.google.android.recaptcha.internal.zzba zzai;
    public static final com.google.android.recaptcha.internal.zzba zzaj;
    public static final com.google.android.recaptcha.internal.zzba zzak;
    public static final com.google.android.recaptcha.internal.zzba zzal;
    public static final com.google.android.recaptcha.internal.zzba zzam;
    public static final com.google.android.recaptcha.internal.zzba zzan;
    public static final com.google.android.recaptcha.internal.zzba zzao;
    public static final com.google.android.recaptcha.internal.zzba zzap;
    public static final com.google.android.recaptcha.internal.zzba zzaq;
    public static final com.google.android.recaptcha.internal.zzba zzar;
    public static final com.google.android.recaptcha.internal.zzba zzas;
    public static final com.google.android.recaptcha.internal.zzba zzat;
    public static final com.google.android.recaptcha.internal.zzba zzau;
    public static final com.google.android.recaptcha.internal.zzba zzav;
    public static final com.google.android.recaptcha.internal.zzba zzaw;
    public static final com.google.android.recaptcha.internal.zzba zzax;
    public static final com.google.android.recaptcha.internal.zzba zzay;
    public static final com.google.android.recaptcha.internal.zzba zzaz;
    public static final com.google.android.recaptcha.internal.zzba zzb;
    public static final com.google.android.recaptcha.internal.zzba zzc;
    public static final com.google.android.recaptcha.internal.zzba zzd;
    public static final com.google.android.recaptcha.internal.zzba zze;
    public static final com.google.android.recaptcha.internal.zzba zzf;
    public static final com.google.android.recaptcha.internal.zzba zzg;
    public static final com.google.android.recaptcha.internal.zzba zzh;
    public static final com.google.android.recaptcha.internal.zzba zzi;
    public static final com.google.android.recaptcha.internal.zzba zzj;
    public static final com.google.android.recaptcha.internal.zzba zzk;
    public static final com.google.android.recaptcha.internal.zzba zzl;
    public static final com.google.android.recaptcha.internal.zzba zzm;
    public static final com.google.android.recaptcha.internal.zzba zzn;
    public static final com.google.android.recaptcha.internal.zzba zzo;
    public static final com.google.android.recaptcha.internal.zzba zzp;
    public static final com.google.android.recaptcha.internal.zzba zzq;
    public static final com.google.android.recaptcha.internal.zzba zzr;
    public static final com.google.android.recaptcha.internal.zzba zzs;
    public static final com.google.android.recaptcha.internal.zzba zzt;
    public static final com.google.android.recaptcha.internal.zzba zzu;
    public static final com.google.android.recaptcha.internal.zzba zzv;
    public static final com.google.android.recaptcha.internal.zzba zzw;
    public static final com.google.android.recaptcha.internal.zzba zzx;
    public static final com.google.android.recaptcha.internal.zzba zzy;
    public static final com.google.android.recaptcha.internal.zzba zzz;
    private final int zzaA;

    static zzba()
    {
        com.google.android.recaptcha.internal.zzba.zza = new com.google.android.recaptcha.internal.zzba(0);
        com.google.android.recaptcha.internal.zzba.zzb = new com.google.android.recaptcha.internal.zzba(8);
        com.google.android.recaptcha.internal.zzba.zzc = new com.google.android.recaptcha.internal.zzba(9);
        com.google.android.recaptcha.internal.zzba.zzd = new com.google.android.recaptcha.internal.zzba(11);
        com.google.android.recaptcha.internal.zzba.zze = new com.google.android.recaptcha.internal.zzba(12);
        com.google.android.recaptcha.internal.zzba.zzf = new com.google.android.recaptcha.internal.zzba(13);
        com.google.android.recaptcha.internal.zzba.zzg = new com.google.android.recaptcha.internal.zzba(14);
        com.google.android.recaptcha.internal.zzba.zzh = new com.google.android.recaptcha.internal.zzba(15);
        com.google.android.recaptcha.internal.zzba.zzi = new com.google.android.recaptcha.internal.zzba(17);
        com.google.android.recaptcha.internal.zzba.zzj = new com.google.android.recaptcha.internal.zzba(20);
        com.google.android.recaptcha.internal.zzba.zzk = new com.google.android.recaptcha.internal.zzba(21);
        com.google.android.recaptcha.internal.zzba.zzl = new com.google.android.recaptcha.internal.zzba(22);
        com.google.android.recaptcha.internal.zzba.zzm = new com.google.android.recaptcha.internal.zzba(23);
        com.google.android.recaptcha.internal.zzba.zzn = new com.google.android.recaptcha.internal.zzba(24);
        com.google.android.recaptcha.internal.zzba.zzo = new com.google.android.recaptcha.internal.zzba(25);
        com.google.android.recaptcha.internal.zzba.zzp = new com.google.android.recaptcha.internal.zzba(26);
        com.google.android.recaptcha.internal.zzba.zzq = new com.google.android.recaptcha.internal.zzba(27);
        com.google.android.recaptcha.internal.zzba.zzr = new com.google.android.recaptcha.internal.zzba(28);
        com.google.android.recaptcha.internal.zzba.zzs = new com.google.android.recaptcha.internal.zzba(29);
        com.google.android.recaptcha.internal.zzba.zzt = new com.google.android.recaptcha.internal.zzba(30);
        com.google.android.recaptcha.internal.zzba.zzu = new com.google.android.recaptcha.internal.zzba(31);
        com.google.android.recaptcha.internal.zzba.zzv = new com.google.android.recaptcha.internal.zzba(32);
        com.google.android.recaptcha.internal.zzba.zzw = new com.google.android.recaptcha.internal.zzba(33);
        com.google.android.recaptcha.internal.zzba.zzx = new com.google.android.recaptcha.internal.zzba(34);
        com.google.android.recaptcha.internal.zzba.zzy = new com.google.android.recaptcha.internal.zzba(35);
        com.google.android.recaptcha.internal.zzba.zzz = new com.google.android.recaptcha.internal.zzba(36);
        com.google.android.recaptcha.internal.zzba.zzA = new com.google.android.recaptcha.internal.zzba(37);
        com.google.android.recaptcha.internal.zzba.zzB = new com.google.android.recaptcha.internal.zzba(38);
        com.google.android.recaptcha.internal.zzba.zzC = new com.google.android.recaptcha.internal.zzba(39);
        com.google.android.recaptcha.internal.zzba.zzD = new com.google.android.recaptcha.internal.zzba(40);
        com.google.android.recaptcha.internal.zzba.zzE = new com.google.android.recaptcha.internal.zzba(41);
        com.google.android.recaptcha.internal.zzba.zzF = new com.google.android.recaptcha.internal.zzba(42);
        com.google.android.recaptcha.internal.zzba.zzG = new com.google.android.recaptcha.internal.zzba(43);
        com.google.android.recaptcha.internal.zzba.zzH = new com.google.android.recaptcha.internal.zzba(44);
        com.google.android.recaptcha.internal.zzba.zzI = new com.google.android.recaptcha.internal.zzba(45);
        com.google.android.recaptcha.internal.zzba.zzJ = new com.google.android.recaptcha.internal.zzba(47);
        com.google.android.recaptcha.internal.zzba.zzK = new com.google.android.recaptcha.internal.zzba(48);
        com.google.android.recaptcha.internal.zzba.zzL = new com.google.android.recaptcha.internal.zzba(49);
        com.google.android.recaptcha.internal.zzba.zzM = new com.google.android.recaptcha.internal.zzba(50);
        com.google.android.recaptcha.internal.zzba.zzN = new com.google.android.recaptcha.internal.zzba(51);
        com.google.android.recaptcha.internal.zzba.zzO = new com.google.android.recaptcha.internal.zzba(52);
        com.google.android.recaptcha.internal.zzba.zzP = new com.google.android.recaptcha.internal.zzba(53);
        com.google.android.recaptcha.internal.zzba.zzQ = new com.google.android.recaptcha.internal.zzba(54);
        com.google.android.recaptcha.internal.zzba.zzR = new com.google.android.recaptcha.internal.zzba(55);
        com.google.android.recaptcha.internal.zzba.zzS = new com.google.android.recaptcha.internal.zzba(56);
        com.google.android.recaptcha.internal.zzba.zzT = new com.google.android.recaptcha.internal.zzba(57);
        com.google.android.recaptcha.internal.zzba.zzU = new com.google.android.recaptcha.internal.zzba(58);
        com.google.android.recaptcha.internal.zzba.zzV = new com.google.android.recaptcha.internal.zzba(59);
        com.google.android.recaptcha.internal.zzba.zzW = new com.google.android.recaptcha.internal.zzba(60);
        com.google.android.recaptcha.internal.zzba.zzX = new com.google.android.recaptcha.internal.zzba(61);
        com.google.android.recaptcha.internal.zzba.zzY = new com.google.android.recaptcha.internal.zzba(67);
        com.google.android.recaptcha.internal.zzba.zzZ = new com.google.android.recaptcha.internal.zzba(64);
        com.google.android.recaptcha.internal.zzba.zzaa = new com.google.android.recaptcha.internal.zzba(66);
        com.google.android.recaptcha.internal.zzba.zzab = new com.google.android.recaptcha.internal.zzba(68);
        com.google.android.recaptcha.internal.zzba.zzac = new com.google.android.recaptcha.internal.zzba(69);
        com.google.android.recaptcha.internal.zzba.zzad = new com.google.android.recaptcha.internal.zzba(70);
        com.google.android.recaptcha.internal.zzba.zzae = new com.google.android.recaptcha.internal.zzba(71);
        com.google.android.recaptcha.internal.zzba.zzaf = new com.google.android.recaptcha.internal.zzba(72);
        com.google.android.recaptcha.internal.zzba.zzag = new com.google.android.recaptcha.internal.zzba(73);
        com.google.android.recaptcha.internal.zzba.zzah = new com.google.android.recaptcha.internal.zzba(74);
        com.google.android.recaptcha.internal.zzba.zzai = new com.google.android.recaptcha.internal.zzba(75);
        com.google.android.recaptcha.internal.zzba.zzaj = new com.google.android.recaptcha.internal.zzba(76);
        com.google.android.recaptcha.internal.zzba.zzak = new com.google.android.recaptcha.internal.zzba(77);
        com.google.android.recaptcha.internal.zzba.zzal = new com.google.android.recaptcha.internal.zzba(78);
        com.google.android.recaptcha.internal.zzba.zzam = new com.google.android.recaptcha.internal.zzba(79);
        com.google.android.recaptcha.internal.zzba.zzan = new com.google.android.recaptcha.internal.zzba(80);
        com.google.android.recaptcha.internal.zzba.zzao = new com.google.android.recaptcha.internal.zzba(81);
        com.google.android.recaptcha.internal.zzba.zzap = new com.google.android.recaptcha.internal.zzba(82);
        com.google.android.recaptcha.internal.zzba.zzaq = new com.google.android.recaptcha.internal.zzba(83);
        com.google.android.recaptcha.internal.zzba.zzar = new com.google.android.recaptcha.internal.zzba(85);
        com.google.android.recaptcha.internal.zzba.zzas = new com.google.android.recaptcha.internal.zzba(89);
        com.google.android.recaptcha.internal.zzba.zzat = new com.google.android.recaptcha.internal.zzba(90);
        com.google.android.recaptcha.internal.zzba.zzau = new com.google.android.recaptcha.internal.zzba(91);
        com.google.android.recaptcha.internal.zzba.zzav = new com.google.android.recaptcha.internal.zzba(92);
        com.google.android.recaptcha.internal.zzba.zzaw = new com.google.android.recaptcha.internal.zzba(93);
        com.google.android.recaptcha.internal.zzba.zzax = new com.google.android.recaptcha.internal.zzba(94);
        com.google.android.recaptcha.internal.zzba.zzay = new com.google.android.recaptcha.internal.zzba(95);
        com.google.android.recaptcha.internal.zzba.zzaz = new com.google.android.recaptcha.internal.zzba(96);
        return;
    }

    public zzba(int p1)
    {
        this.zzaA = p1;
        return;
    }

    public final int zza()
    {
        return this.zzaA;
    }
}
