package okhttp3;
public final class CipherSuite {
    public static final okhttp3.CipherSuite$Companion b;
    public static final okhttp3.CipherSuite$Companion$ORDER_BY_NAME$1 c;
    public static final java.util.LinkedHashMap d;
    public static final okhttp3.CipherSuite e;
    public static final okhttp3.CipherSuite f;
    public static final okhttp3.CipherSuite g;
    public static final okhttp3.CipherSuite h;
    public static final okhttp3.CipherSuite i;
    public static final okhttp3.CipherSuite j;
    public static final okhttp3.CipherSuite k;
    public static final okhttp3.CipherSuite l;
    public static final okhttp3.CipherSuite m;
    public static final okhttp3.CipherSuite n;
    public static final okhttp3.CipherSuite o;
    public static final okhttp3.CipherSuite p;
    public static final okhttp3.CipherSuite q;
    public static final okhttp3.CipherSuite r;
    public static final okhttp3.CipherSuite s;
    public static final okhttp3.CipherSuite t;
    public final String a;

    static CipherSuite()
    {
        okhttp3.CipherSuite$Companion v0_1 = new okhttp3.CipherSuite$Companion(0);
        okhttp3.CipherSuite.b = v0_1;
        okhttp3.CipherSuite.c = new okhttp3.CipherSuite$Companion$ORDER_BY_NAME$1();
        okhttp3.CipherSuite.d = new java.util.LinkedHashMap();
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_WITH_NULL_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_WITH_NULL_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_WITH_RC4_128_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_WITH_DES_CBC_SHA");
        okhttp3.CipherSuite.e = okhttp3.CipherSuite$Companion.a(v0_1, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DH_anon_WITH_RC4_128_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DH_anon_WITH_DES_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_WITH_DES_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_WITH_DES_CBC_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_WITH_RC4_128_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        okhttp3.CipherSuite.f = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite.g = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_NULL_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_PSK_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_PSK_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_PSK_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_SEED_CBC_SHA");
        okhttp3.CipherSuite.h = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite.i = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_FALLBACK_SCSV");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_NULL_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite.j = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite.k = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_anon_WITH_NULL_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        okhttp3.CipherSuite.l = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite.m = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite.n = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite.o = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        okhttp3.CipherSuite.p = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        okhttp3.CipherSuite.q = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        okhttp3.CipherSuite.r = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_AES_128_GCM_SHA256");
        okhttp3.CipherSuite.s = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_AES_256_GCM_SHA384");
        okhttp3.CipherSuite.t = okhttp3.CipherSuite$Companion.a(v0_1, "TLS_CHACHA20_POLY1305_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_AES_128_CCM_SHA256");
        okhttp3.CipherSuite$Companion.a(v0_1, "TLS_AES_128_CCM_8_SHA256");
        return;
    }

    public CipherSuite(String p1)
    {
        this.a = p1;
        return;
    }

    public final String toString()
    {
        return this.a;
    }
}
