package com.google.android.gms.measurement.internal;
public final class zzfy {
    public static final com.google.android.gms.measurement.internal.zzfx zzA;
    public static final com.google.android.gms.measurement.internal.zzfx zzB;
    public static final com.google.android.gms.measurement.internal.zzfx zzC;
    public static final com.google.android.gms.measurement.internal.zzfx zzD;
    public static final com.google.android.gms.measurement.internal.zzfx zzE;
    public static final com.google.android.gms.measurement.internal.zzfx zzF;
    public static final com.google.android.gms.measurement.internal.zzfx zzG;
    public static final com.google.android.gms.measurement.internal.zzfx zzH;
    public static final com.google.android.gms.measurement.internal.zzfx zzI;
    public static final com.google.android.gms.measurement.internal.zzfx zzJ;
    public static final com.google.android.gms.measurement.internal.zzfx zzK;
    public static final com.google.android.gms.measurement.internal.zzfx zzL;
    public static final com.google.android.gms.measurement.internal.zzfx zzM;
    public static final com.google.android.gms.measurement.internal.zzfx zzN;
    public static final com.google.android.gms.measurement.internal.zzfx zzO;
    public static final com.google.android.gms.measurement.internal.zzfx zzP;
    public static final com.google.android.gms.measurement.internal.zzfx zzQ;
    public static final com.google.android.gms.measurement.internal.zzfx zzR;
    public static final com.google.android.gms.measurement.internal.zzfx zzS;
    public static final com.google.android.gms.measurement.internal.zzfx zzT;
    public static final com.google.android.gms.measurement.internal.zzfx zzU;
    public static final com.google.android.gms.measurement.internal.zzfx zzV;
    public static final com.google.android.gms.measurement.internal.zzfx zzW;
    public static final com.google.android.gms.measurement.internal.zzfx zzX;
    public static final com.google.android.gms.measurement.internal.zzfx zzY;
    public static final com.google.android.gms.measurement.internal.zzfx zzZ;
    public static final com.google.android.gms.measurement.internal.zzfx zza;
    public static final com.google.android.gms.measurement.internal.zzfx zzaA;
    public static final com.google.android.gms.measurement.internal.zzfx zzaB;
    public static final com.google.android.gms.measurement.internal.zzfx zzaC;
    public static final com.google.android.gms.measurement.internal.zzfx zzaD;
    public static final com.google.android.gms.measurement.internal.zzfx zzaE;
    public static final com.google.android.gms.measurement.internal.zzfx zzaF;
    public static final com.google.android.gms.measurement.internal.zzfx zzaG;
    public static final com.google.android.gms.measurement.internal.zzfx zzaH;
    public static final com.google.android.gms.measurement.internal.zzfx zzaI;
    public static final com.google.android.gms.measurement.internal.zzfx zzaJ;
    public static final com.google.android.gms.measurement.internal.zzfx zzaK;
    public static final com.google.android.gms.measurement.internal.zzfx zzaL;
    public static final com.google.android.gms.measurement.internal.zzfx zzaM;
    public static final com.google.android.gms.measurement.internal.zzfx zzaN;
    public static final com.google.android.gms.measurement.internal.zzfx zzaO;
    public static final com.google.android.gms.measurement.internal.zzfx zzaP;
    public static final com.google.android.gms.measurement.internal.zzfx zzaQ;
    public static final com.google.android.gms.measurement.internal.zzfx zzaR;
    public static final com.google.android.gms.measurement.internal.zzfx zzaS;
    public static final com.google.android.gms.measurement.internal.zzfx zzaT;
    public static final com.google.android.gms.measurement.internal.zzfx zzaU;
    public static final com.google.android.gms.measurement.internal.zzfx zzaV;
    public static final com.google.android.gms.measurement.internal.zzfx zzaW;
    public static final com.google.android.gms.measurement.internal.zzfx zzaX;
    public static final com.google.android.gms.measurement.internal.zzfx zzaY;
    public static final com.google.android.gms.measurement.internal.zzfx zzaZ;
    public static final com.google.android.gms.measurement.internal.zzfx zzaa;
    public static final com.google.android.gms.measurement.internal.zzfx zzab;
    public static final com.google.android.gms.measurement.internal.zzfx zzac;
    public static final com.google.android.gms.measurement.internal.zzfx zzad;
    public static final com.google.android.gms.measurement.internal.zzfx zzae;
    public static final com.google.android.gms.measurement.internal.zzfx zzaf;
    public static final com.google.android.gms.measurement.internal.zzfx zzag;
    public static final com.google.android.gms.measurement.internal.zzfx zzah;
    public static final com.google.android.gms.measurement.internal.zzfx zzai;
    public static final com.google.android.gms.measurement.internal.zzfx zzaj;
    public static final com.google.android.gms.measurement.internal.zzfx zzak;
    public static final com.google.android.gms.measurement.internal.zzfx zzal;
    public static final com.google.android.gms.measurement.internal.zzfx zzam;
    public static final com.google.android.gms.measurement.internal.zzfx zzan;
    public static final com.google.android.gms.measurement.internal.zzfx zzao;
    public static final com.google.android.gms.measurement.internal.zzfx zzap;
    public static final com.google.android.gms.measurement.internal.zzfx zzaq;
    public static final com.google.android.gms.measurement.internal.zzfx zzar;
    public static final com.google.android.gms.measurement.internal.zzfx zzas;
    public static final com.google.android.gms.measurement.internal.zzfx zzat;
    public static final com.google.android.gms.measurement.internal.zzfx zzau;
    public static final com.google.android.gms.measurement.internal.zzfx zzav;
    public static final com.google.android.gms.measurement.internal.zzfx zzaw;
    public static final com.google.android.gms.measurement.internal.zzfx zzax;
    public static final com.google.android.gms.measurement.internal.zzfx zzay;
    public static final com.google.android.gms.measurement.internal.zzfx zzaz;
    public static final com.google.android.gms.measurement.internal.zzfx zzb;
    public static final com.google.android.gms.measurement.internal.zzfx zzba;
    public static final com.google.android.gms.measurement.internal.zzfx zzbb;
    public static final com.google.android.gms.measurement.internal.zzfx zzbc;
    public static final com.google.android.gms.measurement.internal.zzfx zzbd;
    public static final com.google.android.gms.measurement.internal.zzfx zzbe;
    public static final com.google.android.gms.measurement.internal.zzfx zzbf;
    public static final com.google.android.gms.measurement.internal.zzfx zzbg;
    public static final com.google.android.gms.measurement.internal.zzfx zzbh;
    public static final com.google.android.gms.measurement.internal.zzfx zzbi;
    public static final com.google.android.gms.measurement.internal.zzfx zzbj;
    public static final com.google.android.gms.measurement.internal.zzfx zzbk;
    private static final java.util.List zzbl;
    public static final com.google.android.gms.measurement.internal.zzfx zzc;
    public static final com.google.android.gms.measurement.internal.zzfx zzd;
    public static final com.google.android.gms.measurement.internal.zzfx zze;
    public static final com.google.android.gms.measurement.internal.zzfx zzf;
    public static final com.google.android.gms.measurement.internal.zzfx zzg;
    public static final com.google.android.gms.measurement.internal.zzfx zzh;
    public static final com.google.android.gms.measurement.internal.zzfx zzi;
    public static final com.google.android.gms.measurement.internal.zzfx zzj;
    public static final com.google.android.gms.measurement.internal.zzfx zzk;
    public static final com.google.android.gms.measurement.internal.zzfx zzl;
    public static final com.google.android.gms.measurement.internal.zzfx zzm;
    public static final com.google.android.gms.measurement.internal.zzfx zzn;
    public static final com.google.android.gms.measurement.internal.zzfx zzo;
    public static final com.google.android.gms.measurement.internal.zzfx zzp;
    public static final com.google.android.gms.measurement.internal.zzfx zzq;
    public static final com.google.android.gms.measurement.internal.zzfx zzr;
    public static final com.google.android.gms.measurement.internal.zzfx zzs;
    public static final com.google.android.gms.measurement.internal.zzfx zzt;
    public static final com.google.android.gms.measurement.internal.zzfx zzu;
    public static final com.google.android.gms.measurement.internal.zzfx zzv;
    public static final com.google.android.gms.measurement.internal.zzfx zzw;
    public static final com.google.android.gms.measurement.internal.zzfx zzx;
    public static final com.google.android.gms.measurement.internal.zzfx zzy;
    public static final com.google.android.gms.measurement.internal.zzfx zzz;

    static zzfy()
    {
        com.google.android.gms.measurement.internal.zzfy.zzbl = java.util.Collections.synchronizedList(new java.util.ArrayList());
        java.util.Collections.synchronizedSet(new java.util.HashSet());
        com.google.android.gms.measurement.internal.zzfx v0_2 = Long.valueOf(10000);
        int v3 = 0;
        com.google.android.gms.measurement.internal.zzfy.zza = com.google.android.gms.measurement.internal.zzfy.zza("measurement.ad_id_cache_time", v0_2, v0_2, com.google.android.gms.measurement.internal.zzfq.zza, 0);
        String v1_3 = Long.valueOf(3600000);
        com.google.android.gms.measurement.internal.zzfy.zzb = com.google.android.gms.measurement.internal.zzfy.zza("measurement.app_uninstalled_additional_ad_id_cache_time", v1_3, v1_3, com.google.android.gms.measurement.internal.zzbo.zza, 0);
        Boolean v2_3 = Long.valueOf(86400000);
        com.google.android.gms.measurement.internal.zzfy.zzc = com.google.android.gms.measurement.internal.zzfy.zza("measurement.monitoring.sample_period_millis", v2_3, v2_3, com.google.android.gms.measurement.internal.zzcf.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzd = com.google.android.gms.measurement.internal.zzfy.zza("measurement.config.cache_time", v2_3, v1_3, com.google.android.gms.measurement.internal.zzcq.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zze = com.google.android.gms.measurement.internal.zzfy.zza("measurement.config.url_scheme", "https", "https", com.google.android.gms.measurement.internal.zzdb.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzf = com.google.android.gms.measurement.internal.zzfy.zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", com.google.android.gms.measurement.internal.zzdm.zza, 0);
        String v4_24 = Integer.valueOf(100);
        com.google.android.gms.measurement.internal.zzfy.zzg = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_bundles", v4_24, v4_24, com.google.android.gms.measurement.internal.zzdx.zza, 0);
        String v5_9 = Integer.valueOf(65536);
        com.google.android.gms.measurement.internal.zzfy.zzh = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_batch_size", v5_9, v5_9, com.google.android.gms.measurement.internal.zzei.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzi = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_bundle_size", v5_9, v5_9, com.google.android.gms.measurement.internal.zzet.zza, 0);
        String v5_12 = Integer.valueOf(1000);
        com.google.android.gms.measurement.internal.zzfy.zzj = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_events_per_bundle", v5_12, v5_12, com.google.android.gms.measurement.internal.zzfe.zza, 0);
        int v7_41 = Integer.valueOf(100000);
        com.google.android.gms.measurement.internal.zzfy.zzk = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_events_per_day", v7_41, v7_41, com.google.android.gms.measurement.internal.zzfp.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzl = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_error_events_per_day", v5_12, v5_12, com.google.android.gms.measurement.internal.zzbv.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzm = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_public_events_per_day", Integer.valueOf(50000), Integer.valueOf(50000), com.google.android.gms.measurement.internal.zzbw.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzn = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_conversions_per_day", Integer.valueOf(10000), Integer.valueOf(10000), com.google.android.gms.measurement.internal.zzbx.zza, 0);
        String v8_4 = Integer.valueOf(10);
        com.google.android.gms.measurement.internal.zzfy.zzo = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_realtime_events_per_day", v8_4, v8_4, com.google.android.gms.measurement.internal.zzby.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzp = com.google.android.gms.measurement.internal.zzfy.zza("measurement.store.max_stored_events_per_app", v7_41, v7_41, com.google.android.gms.measurement.internal.zzbz.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzq = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", com.google.android.gms.measurement.internal.zzca.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzr = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", "https://app-measurement.com/s/d", com.google.android.gms.measurement.internal.zzcb.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzs = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.service_upload_apps_list", "", "", com.google.android.gms.measurement.internal.zzcc.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzt = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", "404,429,503,504", com.google.android.gms.measurement.internal.zzcd.zza, 0);
        int v7_9 = Long.valueOf(600000);
        com.google.android.gms.measurement.internal.zzfy.zzu = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.retry_interval", v7_9, v7_9, com.google.android.gms.measurement.internal.zzce.zza, 0);
        String v9_10 = Long.valueOf(21600000);
        com.google.android.gms.measurement.internal.zzfy.zzv = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.retry_max_wait", v9_10, v9_10, com.google.android.gms.measurement.internal.zzcg.zza, 0);
        String v11_7 = Long.valueOf(1800000);
        com.google.android.gms.measurement.internal.zzfy.zzw = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.batch.retry_interval", v11_7, v11_7, com.google.android.gms.measurement.internal.zzch.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzx = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.batch.retry_max_wait", v9_10, v9_10, com.google.android.gms.measurement.internal.zzci.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzy = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.batch.retry_max_count", v8_4, v8_4, com.google.android.gms.measurement.internal.zzcj.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzz = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.max_queued_batches", Integer.valueOf(5000), Integer.valueOf(5000), com.google.android.gms.measurement.internal.zzck.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzA = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.batches_retrieval_limit", Integer.valueOf(5), Integer.valueOf(5), com.google.android.gms.measurement.internal.zzcl.zza, 0);
        String v8_13 = Long.valueOf(5000);
        com.google.android.gms.measurement.internal.zzfy.zzB = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.min_delay_after_startup", v8_13, v8_13, com.google.android.gms.measurement.internal.zzcm.zza, 0);
        String v9_17 = Long.valueOf(1000);
        com.google.android.gms.measurement.internal.zzfy.zzC = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.min_delay_after_broadcast", v9_17, v9_17, com.google.android.gms.measurement.internal.zzcn.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzD = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.upload.min_delay_after_background", v7_9, v7_9, com.google.android.gms.measurement.internal.zzco.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzE = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.batch.long_queuing_threshold", Long.valueOf(14400000), Long.valueOf(14400000), com.google.android.gms.measurement.internal.zzcp.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzF = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.backoff_period", Long.valueOf(43200000), Long.valueOf(43200000), com.google.android.gms.measurement.internal.zzcr.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzG = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.window_interval", v1_3, v1_3, com.google.android.gms.measurement.internal.zzcs.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzH = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.interval", v1_3, v1_3, com.google.android.gms.measurement.internal.zzct.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzI = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.realtime_upload_interval", v0_2, v0_2, com.google.android.gms.measurement.internal.zzcu.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzJ = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.debug_upload_interval", v9_17, v9_17, com.google.android.gms.measurement.internal.zzcv.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzK = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.minimum_delay", Long.valueOf(500), Long.valueOf(500), com.google.android.gms.measurement.internal.zzcw.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzL = com.google.android.gms.measurement.internal.zzfy.zza("measurement.alarm_manager.minimum_interval", Long.valueOf(60000), Long.valueOf(60000), com.google.android.gms.measurement.internal.zzcx.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzM = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.stale_data_deletion_interval", v2_3, v2_3, com.google.android.gms.measurement.internal.zzcy.zza, 0);
        com.google.android.gms.measurement.internal.zzfx v0_12 = Long.valueOf(604800000);
        com.google.android.gms.measurement.internal.zzfy.zzN = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.refresh_blacklisted_config_interval", v0_12, v0_12, com.google.android.gms.measurement.internal.zzcz.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzO = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.initial_upload_delay_time", Long.valueOf(15000), Long.valueOf(15000), com.google.android.gms.measurement.internal.zzda.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzP = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.retry_time", v11_7, v11_7, com.google.android.gms.measurement.internal.zzdc.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzQ = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.retry_count", Integer.valueOf(6), Integer.valueOf(6), com.google.android.gms.measurement.internal.zzdd.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzR = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_queue_time", Long.valueOf(518400000), Long.valueOf(518400000), com.google.android.gms.measurement.internal.zzde.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzS = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.google_signal_max_queue_time", Long.valueOf(300000), Long.valueOf(300000), com.google.android.gms.measurement.internal.zzdf.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzT = com.google.android.gms.measurement.internal.zzfy.zza("measurement.lifetimevalue.max_currency_tracked", Integer.valueOf(4), Integer.valueOf(4), com.google.android.gms.measurement.internal.zzdg.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzU = com.google.android.gms.measurement.internal.zzfy.zza("measurement.audience.filter_result_max_count", Integer.valueOf(200), Integer.valueOf(200), com.google.android.gms.measurement.internal.zzdh.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzV = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_public_user_properties", v4_24, v4_24, 0, 0);
        com.google.android.gms.measurement.internal.zzfy.zzW = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_event_name_cardinality", Integer.valueOf(2000), Integer.valueOf(2000), 0, 0);
        com.google.android.gms.measurement.internal.zzfy.zzX = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_public_event_params", v4_24, v4_24, 0, 0);
        com.google.android.gms.measurement.internal.zzfy.zzY = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service_client.idle_disconnect_millis", v8_13, v8_13, com.google.android.gms.measurement.internal.zzdi.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzZ = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service_client.reconnect_millis", v9_17, v9_17, com.google.android.gms.measurement.internal.zzdj.zza, 0);
        Boolean v2_34 = Boolean.FALSE;
        com.google.android.gms.measurement.internal.zzfy.zzaa = com.google.android.gms.measurement.internal.zzfy.zza("measurement.test.boolean_flag", v2_34, v2_34, com.google.android.gms.measurement.internal.zzdk.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzab = com.google.android.gms.measurement.internal.zzfy.zza("measurement.test.string_flag", "---", "---", com.google.android.gms.measurement.internal.zzdl.zza, 0);
        String v8_20 = Long.valueOf(-1);
        com.google.android.gms.measurement.internal.zzfy.zzac = com.google.android.gms.measurement.internal.zzfy.zza("measurement.test.long_flag", v8_20, v8_20, com.google.android.gms.measurement.internal.zzdn.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zza("measurement.test.cached_long_flag", v8_20, v8_20, com.google.android.gms.measurement.internal.zzdo.zza, 1);
        com.google.android.gms.measurement.internal.zzfy.zzad = com.google.android.gms.measurement.internal.zzfy.zza("measurement.test.int_flag", Integer.valueOf(-2), Integer.valueOf(-2), com.google.android.gms.measurement.internal.zzdp.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzae = com.google.android.gms.measurement.internal.zzfy.zza("measurement.test.double_flag", Double.valueOf(-4609434218613702656), Double.valueOf(-4609434218613702656), com.google.android.gms.measurement.internal.zzdq.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaf = com.google.android.gms.measurement.internal.zzfy.zza("measurement.experiment.max_ids", Integer.valueOf(50), Integer.valueOf(50), com.google.android.gms.measurement.internal.zzdr.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzag = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_item_scoped_custom_parameters", Integer.valueOf(27), Integer.valueOf(27), com.google.android.gms.measurement.internal.zzds.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzah = com.google.android.gms.measurement.internal.zzfy.zza("measurement.upload.max_event_parameter_value_length", Integer.valueOf(500), Integer.valueOf(500), com.google.android.gms.measurement.internal.zzdt.zza, 1);
        com.google.android.gms.measurement.internal.zzfy.zzai = com.google.android.gms.measurement.internal.zzfy.zza("measurement.max_bundles_per_iteration", v4_24, v4_24, com.google.android.gms.measurement.internal.zzdu.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaj = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sdk.attribution.cache.ttl", v0_12, v0_12, com.google.android.gms.measurement.internal.zzdv.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzak = com.google.android.gms.measurement.internal.zzfy.zza("measurement.redaction.app_instance_id.ttl", Long.valueOf(7200000), Long.valueOf(7200000), com.google.android.gms.measurement.internal.zzdw.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzal = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.client.min_ad_services_version", Integer.valueOf(7), Integer.valueOf(7), com.google.android.gms.measurement.internal.zzdy.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzam = com.google.android.gms.measurement.internal.zzfy.zza("measurement.dma_consent.max_daily_dcu_realtime_events", Integer.valueOf(1), Integer.valueOf(1), com.google.android.gms.measurement.internal.zzdz.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzan = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.uri_scheme", "https", "https", com.google.android.gms.measurement.internal.zzea.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzao = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.uri_authority", "google-analytics.com", "google-analytics.com", com.google.android.gms.measurement.internal.zzeb.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzap = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", "privacy-sandbox/register-app-conversion", com.google.android.gms.measurement.internal.zzec.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaq = com.google.android.gms.measurement.internal.zzfy.zza("measurement.session.engagement_interval", v1_3, v1_3, com.google.android.gms.measurement.internal.zzed.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzar = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.app_allowlist", "", "", com.google.android.gms.measurement.internal.zzee.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzas = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", "_npa,npa|_fot,fot", com.google.android.gms.measurement.internal.zzef.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzat = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.event_params", "value|currency", "value|currency", com.google.android.gms.measurement.internal.zzeg.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzau = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.query_parameters_to_remove", "", "", com.google.android.gms.measurement.internal.zzeh.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzav = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.max_queue_time", Long.valueOf(864000000), Long.valueOf(864000000), com.google.android.gms.measurement.internal.zzej.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaw = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.max_retry_delay_seconds", Integer.valueOf(16), Integer.valueOf(16), com.google.android.gms.measurement.internal.zzek.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzax = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.client.min_time_after_boot_seconds", Integer.valueOf(90), Integer.valueOf(90), com.google.android.gms.measurement.internal.zzel.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.max_trigger_uris_queried_at_once", Integer.valueOf(v3), Integer.valueOf(v3), com.google.android.gms.measurement.internal.zzem.zza, v3);
        com.google.android.gms.measurement.internal.zzfy.zzay = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.max_trigger_registrations_per_day", v5_12, v5_12, com.google.android.gms.measurement.internal.zzen.zza, 0);
        com.google.android.gms.measurement.internal.zzfx v0_51 = Boolean.TRUE;
        com.google.android.gms.measurement.internal.zzfy.zzaz = com.google.android.gms.measurement.internal.zzfy.zza("measurement.config.bundle_for_all_apps_on_backgrounded", v0_51, v0_51, com.google.android.gms.measurement.internal.zzeo.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaA = com.google.android.gms.measurement.internal.zzfy.zza("measurement.config.notify_trigger_uris_on_backgrounded", v0_51, v0_51, com.google.android.gms.measurement.internal.zzep.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaB = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.notify_app_delay_millis", Integer.valueOf(3000), Integer.valueOf(3000), com.google.android.gms.measurement.internal.zzeq.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaC = com.google.android.gms.measurement.internal.zzfy.zza("measurement.quality.checksum", v2_34, v2_34, 0, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaD = com.google.android.gms.measurement.internal.zzfy.zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", v2_34, v2_34, com.google.android.gms.measurement.internal.zzer.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaE = com.google.android.gms.measurement.internal.zzfy.zza("measurement.audience.refresh_event_count_filters_timestamp", v2_34, v2_34, com.google.android.gms.measurement.internal.zzes.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaF = com.google.android.gms.measurement.internal.zzfy.zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", v2_34, v2_34, com.google.android.gms.measurement.internal.zzeu.zza, 1);
        com.google.android.gms.measurement.internal.zzfy.zzaG = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", v2_34, v2_34, com.google.android.gms.measurement.internal.zzev.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaH = com.google.android.gms.measurement.internal.zzfy.zza("measurement.integration.disable_firebase_instance_id", v2_34, v2_34, com.google.android.gms.measurement.internal.zzew.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaI = com.google.android.gms.measurement.internal.zzfy.zza("measurement.collection.service.update_with_analytics_fix", v2_34, v2_34, com.google.android.gms.measurement.internal.zzex.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaJ = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service.storage_consent_support_version", Integer.valueOf(203600), Integer.valueOf(203600), com.google.android.gms.measurement.internal.zzey.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaK = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service.store_null_safelist", v0_51, v0_51, com.google.android.gms.measurement.internal.zzez.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaL = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service.store_safelist", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfa.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaM = com.google.android.gms.measurement.internal.zzfy.zza("measurement.session_stitching_token_enabled", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfb.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaN = com.google.android.gms.measurement.internal.zzfy.zza("measurement.sgtm.client.upload_on_backgrounded.dev", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfc.zza, 1);
        com.google.android.gms.measurement.internal.zzfy.zzaO = com.google.android.gms.measurement.internal.zzfy.zza("measurement.gmscore_client_telemetry", v2_34, v2_34, com.google.android.gms.measurement.internal.zzft.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaP = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.service", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfd.zza, 1);
        com.google.android.gms.measurement.internal.zzfy.zzaQ = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.client2", v0_51, v0_51, com.google.android.gms.measurement.internal.zzff.zza, 1);
        com.google.android.gms.measurement.internal.zzfy.zzaR = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.uuid_generation", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfg.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaS = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.enable_trigger_redaction", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfh.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.followup1.service", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfi.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaT = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.retry_disposition", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfj.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaU = com.google.android.gms.measurement.internal.zzfy.zza("measurement.client.sessions.enable_fix_background_engagement", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfw.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaV = com.google.android.gms.measurement.internal.zzfy.zza("measurement.set_default_event_parameters_propagate_clear.service.dev", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfk.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaW = com.google.android.gms.measurement.internal.zzfy.zza("measurement.set_default_event_parameters_propagate_clear.client.dev", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfl.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaX = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service.ad_impression.convert_value_to_double", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfm.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", v0_51, v0_51, com.google.android.gms.measurement.internal.zzfn.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zza("measurement.remove_conflicting_first_party_apis.dev", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfo.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaY = com.google.android.gms.measurement.internal.zzfy.zza("measurement.rb.attribution.service.trigger_uris_high_priority", v0_51, v0_51, com.google.android.gms.measurement.internal.zzbp.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzaZ = com.google.android.gms.measurement.internal.zzfy.zza("measurement.tcf.consent_fix", v0_51, v0_51, com.google.android.gms.measurement.internal.zzbq.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzba = com.google.android.gms.measurement.internal.zzfy.zza("measurement.experiment.enable_phenotype_experiment_reporting", v0_51, v0_51, com.google.android.gms.measurement.internal.zzbr.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbb = com.google.android.gms.measurement.internal.zzfy.zza("measurement.set_default_event_parameters.fix_service_request_ordering", v2_34, v2_34, com.google.android.gms.measurement.internal.zzbj.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbc = com.google.android.gms.measurement.internal.zzfy.zza("measurement.set_default_event_parameters.fix_app_update_logging", v0_51, v0_51, com.google.android.gms.measurement.internal.zzbi.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbd = com.google.android.gms.measurement.internal.zzfy.zza("measurement.service.fix_stop_bundling_bug", v0_51, v0_51, com.google.android.gms.measurement.internal.zzbm.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbe = com.google.android.gms.measurement.internal.zzfy.zza("measurement.fix_params_logcat_spam", v0_51, v0_51, com.google.android.gms.measurement.internal.zzbl.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbf = com.google.android.gms.measurement.internal.zzfy.zza("measurement.gbraid_campaign.stop_lgclid", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfs.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbg = com.google.android.gms.measurement.internal.zzfy.zza("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", "gclid,gbraid,gad_campaignid", com.google.android.gms.measurement.internal.zzbs.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbh = com.google.android.gms.measurement.internal.zzfy.zza("measurement.edpb.service", v2_34, v2_34, com.google.android.gms.measurement.internal.zzbk.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbi = com.google.android.gms.measurement.internal.zzfy.zza("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", "_f,_v,_cmp", com.google.android.gms.measurement.internal.zzbt.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbj = com.google.android.gms.measurement.internal.zzfy.zza("measurement.add_first_launch_logging_timestamp.service", v2_34, v2_34, com.google.android.gms.measurement.internal.zzfv.zza, 0);
        com.google.android.gms.measurement.internal.zzfy.zzbk = com.google.android.gms.measurement.internal.zzfy.zza("measurement.overlapping_bundles_fix", v2_34, v2_34, com.google.android.gms.measurement.internal.zzbu.zza, 0);
        return;
    }

    public static com.google.android.gms.measurement.internal.zzfx zza(String p6, Object p7, Object p8, com.google.android.gms.measurement.internal.zzbn p9, boolean p10)
    {
        com.google.android.gms.measurement.internal.zzfx v0_1 = new com.google.android.gms.measurement.internal.zzfx(p6, p7, p8, p9, 0);
        if (p10) {
            com.google.android.gms.measurement.internal.zzfy.zzbl.add(v0_1);
        }
        return v0_1;
    }

    public static synthetic java.util.List zzb()
    {
        return com.google.android.gms.measurement.internal.zzfy.zzbl;
    }
}
