package com.google.android.gms.measurement.internal;
public final class zzjn {
    public static final String[] zza;
    public static final String[] zzb;
    public static final String[] zzc;
    public static final String[] zzd;

    static zzjn()
    {
        String v3 = "exposure_time";
        String v5 = "ad_unit_id";
        String v7 = "ga_error_value";
        String v9 = "ga_event_origin";
        String v11 = "ga_screen_class";
        String v13 = "ga_previous_screen";
        String v15 = "ga_previous_id";
        String v17 = "message_device_time";
        String v19 = "message_name";
        String v21 = "message_tracking_id";
        String v23 = "previous_app_version";
        String v25 = "topic";
        String v27 = "previous_first_open_count";
        String v29 = "system_app_update";
        String v31 = "ga_event_id";
        String v33 = "ga_group_name";
        String v35 = "ga_index";
        String v37 = "campaign_info_source";
        String v39 = "deferred_analytics_collection";
        String v41 = "ga_session_id";
        String v43 = "app_in_background";
        String v45 = "customer_type";
        String v47 = "firebase_error";
        String v49 = "firebase_error_length";
        String v51 = "firebase_screen";
        String v53 = "firebase_screen_id";
        String v55 = "firebase_previous_class";
        com.google.android.gms.measurement.internal.zzjn.zza = new String[] {"ga_conversion", "session_id"});
        v3 = "_xt";
        v5 = "_ai";
        v7 = "_ev";
        v9 = "_o";
        v11 = "_sc";
        v13 = "_pn";
        v15 = "_pi";
        v17 = "_ndt";
        v19 = "_nmn";
        v21 = "_nmtid";
        v23 = "_pv";
        v25 = "_nt";
        v27 = "_pfo";
        v29 = "_sysu";
        v31 = "_eid";
        v33 = "_gn";
        v35 = "_i";
        v37 = "_cis";
        v39 = "_dac";
        v41 = "_sid";
        v43 = "_aib";
        v45 = "_ct";
        v47 = "_err";
        v49 = "_el";
        v51 = "_sn";
        v53 = "_si";
        v55 = "_pc";
        com.google.android.gms.measurement.internal.zzjn.zzb = new String[] {"_c", "_sid"});
        com.google.android.gms.measurement.internal.zzjn.zzc = new String[] {"items"});
        v3 = "creative_name";
        v5 = "currency";
        v7 = "discount";
        v9 = "item_id";
        v11 = "item_category";
        v13 = "item_category3";
        v15 = "item_category5";
        v17 = "item_list_id";
        v19 = "item_variant";
        v21 = "payment_type";
        v23 = "promotion_id";
        v25 = "quantity";
        v27 = "shipping_tier";
        v29 = "transaction_id";
        v31 = "item_list";
        com.google.android.gms.measurement.internal.zzjn.zzd = new String[] {"affiliation", "item_location_id"});
        return;
    }
}
