package com.google.android.gms.fido;
public final class zza {
    public static final com.google.android.gms.common.Feature zza;
    public static final com.google.android.gms.common.Feature zzb;
    public static final com.google.android.gms.common.Feature zzc;
    public static final com.google.android.gms.common.Feature zzd;
    public static final com.google.android.gms.common.Feature zze;
    public static final com.google.android.gms.common.Feature zzf;
    public static final com.google.android.gms.common.Feature zzg;
    public static final com.google.android.gms.common.Feature zzh;
    public static final com.google.android.gms.common.Feature zzi;
    public static final com.google.android.gms.common.Feature zzj;
    public static final com.google.android.gms.common.Feature zzk;
    public static final com.google.android.gms.common.Feature zzl;
    public static final com.google.android.gms.common.Feature zzm;
    public static final com.google.android.gms.common.Feature zzn;
    public static final com.google.android.gms.common.Feature zzo;
    public static final com.google.android.gms.common.Feature zzp;
    public static final com.google.android.gms.common.Feature zzq;
    public static final com.google.android.gms.common.Feature zzr;
    public static final com.google.android.gms.common.Feature zzs;
    public static final com.google.android.gms.common.Feature zzt;
    public static final com.google.android.gms.common.Feature zzu;
    public static final com.google.android.gms.common.Feature zzv;
    public static final com.google.android.gms.common.Feature zzw;
    public static final com.google.android.gms.common.Feature zzx;
    public static final com.google.android.gms.common.Feature zzy;
    public static final com.google.android.gms.common.Feature[] zzz;

    static zza()
    {
        com.google.android.gms.common.Feature v1_3 = new com.google.android.gms.common.Feature("cancel_target_direct_transfer", 1);
        com.google.android.gms.fido.zza.zza = v1_3;
        com.google.android.gms.common.Feature[] v0_12 = new com.google.android.gms.common.Feature("delete_credential", 1);
        com.google.android.gms.fido.zza.zzb = v0_12;
        com.google.android.gms.fido.zza.zzc = new com.google.android.gms.common.Feature("delete_device_public_key", 1);
        com.google.android.gms.fido.zza.zzd = new com.google.android.gms.common.Feature("get_or_generate_device_public_key", 1);
        com.google.android.gms.fido.zza.zze = new com.google.android.gms.common.Feature("get_passkeys", 1);
        com.google.android.gms.fido.zza.zzf = new com.google.android.gms.common.Feature("update_passkey", 1);
        com.google.android.gms.fido.zza.zzg = new com.google.android.gms.common.Feature("is_user_verifying_platform_authenticator_available_for_credential", 1);
        com.google.android.gms.fido.zza.zzh = new com.google.android.gms.common.Feature("is_user_verifying_platform_authenticator_available", 1);
        com.google.android.gms.fido.zza.zzi = new com.google.android.gms.common.Feature("privileged_api_list_credentials", 2);
        com.google.android.gms.fido.zza.zzj = new com.google.android.gms.common.Feature("start_target_direct_transfer", 1);
        com.google.android.gms.fido.zza.zzk = new com.google.android.gms.common.Feature("first_party_api_get_link_info", 1);
        com.google.android.gms.fido.zza.zzl = new com.google.android.gms.common.Feature("zero_party_api_register", 3);
        com.google.android.gms.common.Feature v2_3 = new com.google.android.gms.common.Feature("zero_party_api_sign", 3);
        com.google.android.gms.fido.zza.zzm = v2_3;
        com.google.android.gms.common.Feature v20 = v0_12;
        com.google.android.gms.common.Feature v13 = v1_3;
        com.google.android.gms.fido.zza.zzn = new com.google.android.gms.common.Feature("zero_party_api_list_discoverable_credentials", 2);
        com.google.android.gms.common.Feature v18 = v2_3;
        com.google.android.gms.fido.zza.zzo = new com.google.android.gms.common.Feature("zero_party_api_authenticate_passkey", 1);
        com.google.android.gms.common.Feature[] v0_15 = new com.google.android.gms.common.Feature("zero_party_api_register_passkey", 1);
        com.google.android.gms.fido.zza.zzp = v0_15;
        com.google.android.gms.common.Feature v17 = v0_15;
        com.google.android.gms.common.Feature v3_13 = new com.google.android.gms.common.Feature("zero_party_api_register_passkey_with_sync_account", 1);
        com.google.android.gms.fido.zza.zzq = v3_13;
        com.google.android.gms.common.Feature v19 = v3_13;
        com.google.android.gms.common.Feature[] v0_18 = new com.google.android.gms.common.Feature("zero_party_api_get_hybrid_client_registration_pending_intent", 1);
        com.google.android.gms.fido.zza.zzr = v0_18;
        com.google.android.gms.common.Feature v21 = v0_18;
        com.google.android.gms.common.Feature v3_16 = new com.google.android.gms.common.Feature("zero_party_api_get_hybrid_client_sign_pending_intent", 1);
        com.google.android.gms.fido.zza.zzs = v3_16;
        com.google.android.gms.common.Feature v22 = v3_16;
        com.google.android.gms.common.Feature[] v0_1 = new com.google.android.gms.common.Feature("get_browser_hybrid_client_sign_pending_intent", 1);
        com.google.android.gms.fido.zza.zzt = v0_1;
        com.google.android.gms.common.Feature v23 = v0_1;
        com.google.android.gms.common.Feature v3_2 = new com.google.android.gms.common.Feature("get_browser_hybrid_client_registration_pending_intent", 1);
        com.google.android.gms.fido.zza.zzu = v3_2;
        com.google.android.gms.common.Feature v24 = v3_2;
        com.google.android.gms.common.Feature[] v0_4 = new com.google.android.gms.common.Feature("privileged_authenticate_passkey", 1);
        com.google.android.gms.fido.zza.zzv = v0_4;
        com.google.android.gms.common.Feature v25_0 = v0_4;
        com.google.android.gms.common.Feature v3_5 = new com.google.android.gms.common.Feature("privileged_register_passkey_with_sync_account", 1);
        com.google.android.gms.fido.zza.zzw = v3_5;
        com.google.android.gms.common.Feature v26 = v3_5;
        com.google.android.gms.fido.zza.zzx = new com.google.android.gms.common.Feature("zero_party_api_get_privileged_hybrid_client_registration_pending_intent", 1);
        com.google.android.gms.common.Feature v3_8 = new com.google.android.gms.common.Feature("zero_party_api_get_privileged_hybrid_client_sign_pending_intent", 1);
        com.google.android.gms.fido.zza.zzy = v3_8;
        com.google.android.gms.common.Feature v16 = v17;
        v17 = v19;
        v19 = v22;
        v22 = v25_0;
        com.google.android.gms.common.Feature v1_2 = v13;
        v13 = v18;
        com.google.android.gms.common.Feature v2 = v20;
        v18 = v21;
        v20 = v23;
        v21 = v24;
        v23 = v26;
        com.google.android.gms.fido.zza.zzz = new com.google.android.gms.common.Feature[] {v1_2, v3_8});
        return;
    }
}
