package com.google.android.gms.common.api.internal;
public final class zacp extends com.google.android.gms.common.api.PendingResult {
    private final com.google.android.gms.common.api.Status zaa;

    public zacp(com.google.android.gms.common.api.Status p3)
    {
        com.google.android.gms.common.internal.Preconditions.checkNotNull(p3, "Status must not be null");
        com.google.android.gms.common.internal.Preconditions.checkArgument((p3.isSuccess() ^ 1), "Status must not be success");
        this.zaa = p3;
        return;
    }

    public final void addStatusListener(com.google.android.gms.common.api.PendingResult$StatusListener p2)
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final com.google.android.gms.common.api.Result await()
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final com.google.android.gms.common.api.Result await(long p1, java.util.concurrent.TimeUnit p3)
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void cancel()
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final boolean isCanceled()
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void setResultCallback(com.google.android.gms.common.api.ResultCallback p2)
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void setResultCallback(com.google.android.gms.common.api.ResultCallback p1, long p2, java.util.concurrent.TimeUnit p4)
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final com.google.android.gms.common.api.TransformedResult then(com.google.android.gms.common.api.ResultTransform p2)
    {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final com.google.android.gms.common.api.Status zaa()
    {
        return this.zaa;
    }
}
